apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-svc-new-test2-svc-new-test2-svc-new-test2-svc-new-test2-svc-new-test2-svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-svc-new-test2-svc-new-test2-svc-new-test2-svc-new-test2-svc-new-test2-svc
