apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: net-tools-api
    meta.helm.sh/release-namespace: rtf2-health
    rtf.mulesoft.com/desiredStatus: STARTED
    rtf.mulesoft.com/last-publish-hash: 2af63e04be541872f3929cdcd7e13103
    rtf.mulesoft.com/replicas: "1"
    rtf.mulesoft.com/version: dad0c042-1a51-4d5e-9963-f1dd3b9ed897
  labels:
    app.kubernetes.io/managed-by: Helm
    environment: 9643d5d7-bfc5-4e6f-94f4-6d941387d401
    organization: 56c14f77-79ed-4de3-8313-d542ea9f232b
    rtf.mulesoft.com/agentNamespace: rtf
    rtf.mulesoft.com/id: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
    rtf.mulesoft.com/status: READY
    rtf.mulesoft.com/version: dad0c042-1a51-4d5e-9963-f1dd3b9ed897
    type: MuleApplication
  name: net-tools-api
  namespace: rtf2-health
spec:
  progressDeadlineSeconds: 720
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      rtf.mulesoft.com/id: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        mulesoft.com/resources: '[{"url":"https://configuration-resolver.prod.cloudhub.io/api/v1/deployments/c5a684dc-ae10-47e0-bd7a-509cc1b037fe/assets/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJNdWxlU29mdCAtIEFNQyAtIERlcGxveWVyIiwiZ3JvdXBJZCI6IjU2YzE0Zjc3LTc5ZWQtNGRlMy04MzEzLWQ1NDJlYTlmMjMyYiIsImNsYXNzaWZpZXIiOiJtdWxlLWFwcGxpY2F0aW9uIiwiYXJ0aWZhY3RJZCI6Im5ldC10b29scy1hcGktMi41LjEtbXVsZS1hcHBsaWNhdGlvbiIsInBhY2thZ2luZyI6ImphciIsImV4Y2hhbmdlVHlwZSI6ImFwcCIsImRlcGxveW1lbnROYW1lIjoibmV0LXRvb2xzLWFwaSIsInNvdXJjZSI6ImV4Y2hhbmdlIiwicmVmSWQiOiJuZXQtdG9vbHMtYXBpIiwidmVyc2lvbiI6IjEuMC4zIiwiYXVkIjoiMjk0NDM5ZjMtYzA4MC00YzFkLTk1OTAtYjcwMzlkZDNjOTE1Lk1DLnVzLWVhc3QtMSJ9.a6NfArvakAsH6HSd0v1DGAHOF6sY0NmNx1Vqo-5HY_KTnZBIL5LDeF5-jPSqyNXaDro3ZA96ODsQGNJN3ntA8WWMVSy6qA2NFpmyN87RCie9HGRx4N46tfAT7osYIexJ42Hv_HEKaNgYMooVjzjQtUvtUUo14vcv70JcrsbtNKdOR0n8UDJGlG7uKqQVumCG0jvz1pgpJwgCfVvYioLJ0PwMqV_kv_c6k039r3-y3fR6ufcHC-6_5CZI9vSKsutnVB2jqMOyNNltGsBQa1Z-7ziSbU4f6i4pBEHEqUlpjbwsy8mXtFLFa98LMSozpxso1-OwZoi4NNy3g0sAoOcRTA","destinationFile":"/opt/mule/deployments/net-tools-api.jar"}]'
      labels:
        am-org-id: 56c14f77-79ed-4de3-8313-d542ea9f232b
        app: net-tools-api
        environment: 9643d5d7-bfc5-4e6f-94f4-6d941387d401
        name: net-tools-api
        organization: 56c14f77-79ed-4de3-8313-d542ea9f232b
        root-org-id: 56c14f77-79ed-4de3-8313-d542ea9f232b
        rtf.mulesoft.com/generation: 0d64f3e4a98bdde991276cfcd62f9a56
        rtf.mulesoft.com/id: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
        type: MuleApplication
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: rtf.mulesoft.com/id
                  operator: In
                  values:
                  - c5a684dc-ae10-47e0-bd7a-509cc1b037fe
                - key: rtf.mulesoft.com/generation
                  operator: In
                  values:
                  - 0d64f3e4a98bdde991276cfcd62f9a56
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - env:
        - name: APP_NAME
          value: net-tools-api
        - name: TARGET_ID
          value: 294439f3-c080-4c1d-9590-b7039dd3c915
        - name: DEPLOYMENT_ID
          value: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
        - name: RTF_ID
          value: 294439f3-c080-4c1d-9590-b7039dd3c915
        - name: CONF_PATH
          value: /opt/mule/deployments/conf/net-tools-api.yml
        - name: POD_CPU_REQUEST
          value: 20m
        - name: POD_CPU_LIMIT
          value: 500m
        - name: POD_MEM_REQUEST
          value: 1000Mi
        - name: POD_MEM_LIMIT
          value: 1000Mi
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ROOT_ORG_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['root-org-id']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ORG_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['organization']
        - name: ENV_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['environment']
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MULE_SECURE_PROPERTIES
          valueFrom:
            secretKeyRef:
              key: properties
              name: secure-properties
              optional: true
        - name: INFLUX_PUBLISH_HEAP_METRICS_DISABLED
          value: "true"
        - name: USE_PROXY_PROPERTIES
          value: "false"
        - name: ENABLE_CONSOLE_LOG
          value: "true"
        envFrom:
        - secretRef:
            name: custom-properties
            optional: true
        - secretRef:
            name: env-c5a684dc-ae10-47e0-bd7a-509cc1b037fe
            optional: true
        image: rtf-runtime-registry.kprod.msap.io/mulesoft/poseidon-runtime-4.6.0:40e-java8
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: app
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8082
          name: https
          protocol: TCP
        - containerPort: 5701
          name: hazelcast
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /readiness-probe.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsUser: 2020
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/overlay
          name: overlay
        - mountPath: /opt/mule/deployments/conf
          name: opt-mule-deployments-conf
        - mountPath: /tmp
          name: tmp
        - mountPath: /license
          name: mulelicense
          readOnly: true
      - env:
        - name: APP_NAME
          value: net-tools-api
        - name: TARGET_ID
          value: 294439f3-c080-4c1d-9590-b7039dd3c915
        - name: CLUSTER_FLAVOR
          value: byok
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ROOT_ORG_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['root-org-id']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ORG_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['organization']
        - name: ENV_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['environment']
        - name: DEPLOYMENT_ID
          value: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
        - name: APP_REGION
          value: us-east-1
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: LOG_LOCATION
          value: /mnt/overlay/opt/mule/logs/_*metric.log
        - name: DATA_PATH
          value: /mnt/overlay/am-data
        - name: PROXY_URL
          valueFrom:
            secretKeyRef:
              key: MONITORING_PROXY
              name: custom-properties
              optional: true
        - name: INGEST_HOST
          value: dias-ingestor-router.us-east-1.prod.cloudhub.io:443
        - name: INGEST_HOST_LEGACY
          value: dias-ingestor-nginx.prod.cloudhub.io:5044
        - name: MULE_BILLING_ENABLED
          value: "false"
        - name: MULE_METERING_ENABLED
          value: "true"
        - name: MULE_VERSION
          value: 4.6.0:40e-java8
        image: rtf-runtime-registry.kprod.msap.io/mulesoft/dias-anypoint-monitoring-sidecar:v1.3.90
        imagePullPolicy: IfNotPresent
        name: anypoint-monitoring
        resources:
          limits:
            cpu: 150m
            memory: 70Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsUser: 2001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /mnt/overlay
          name: overlay
        - mountPath: /data/certs
          name: monitoring-certs
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
      - name: rtf-pull-secret
      initContainers:
      - args:
        - --namespace
        - rtf
        image: rtf-runtime-registry.kprod.msap.io/mulesoft/rtf-app-init:v1.0.141
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        securityContext:
          runAsUser: 2020
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
          readOnly: true
        - mountPath: /mnt/overlay
          name: overlay
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: net-tools-api
      serviceAccountName: net-tools-api
      terminationGracePeriodSeconds: 300
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            rtf.mulesoft.com/generation: 0d64f3e4a98bdde991276cfcd62f9a56
            rtf.mulesoft.com/id: c5a684dc-ae10-47e0-bd7a-509cc1b037fe
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - emptyDir: {}
        name: overlay
      - configMap:
          defaultMode: 420
          name: c5a684dc-ae10-47e0-bd7a-509cc1b037fe-0
        name: opt-mule-deployments-conf
      - emptyDir: {}
        name: tmp
      - name: mulelicense
        secret:
          defaultMode: 420
          items:
          - key: "3"
            path: muleLicenseKey.lic
          secretName: rtf-muleruntime-license
      - name: monitoring-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: rtf-monitoring-certificate
