# This is a basic workflow to help you get started with Actions

name: api-deployment-runtime-fabric

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashfiles('**/pom.xml') }}
          restore-key: |
            ${{ runner.os }}-maven-

      - name: add repo credentials
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "mule-enterprise",
              "username": "mikeyumi",
              "password": "@@@@Warcarft1234"
            }]

      - name: print logs
        run: mvn help:effective-settings

      - name: build with maven
        run: |
          pwd
          mvn -B package --file apis/american-flights-api/pom.xml
          
      - name: stamp artifact
        run: |
          artifactName1=$(ls apis/american-flights-api/target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls apis/american-flights-api/target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1  $artifactName2

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: apis/american-flights-api/target/*.jar
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashfiles('**/pom.xml') }}
          restore-key: |
            ${{ runner.os }}-maven-
            
      - uses: actions/download-artifact@master
        with:
          name: artifact
          
      - name: deploy to Sandbox
        env: 
          USERNAME: "mikeyumi"
          PASSWORD: "@@@@Warcarft1234"
        run: |
          pwd
          cd apis/american-flights-api
          pwd
          artifactName=$(ls target/*.jar | head -1)
          mvn deploy -DmuleDeploy -e \
            -Dmule.artifact=$artifactName \
            -Danypoint.username="$USERNAME" \
            -Danypoint.password="$PASSWORD"
