# This is a basic workflow to help you get started with Actions

name: Updating Memory and CPU in Resource-Cache.yaml
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # ClientId of the Azure Service principal created.
    
       # kubectl config get-contexts
       # kubectl config use-context nonpd-aks-02
       # kubectl patch deployment resource-cache -n rtf --patch-file resource-cache-patch-file.yaml
            
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          inlineScript: |
            ls
            az aks command invoke --name nonpd-aks-02 --resource-group 227925-dev-eus2-nonpd-rg --command "kubectl config use-context nonpd-aks-02"
            az aks command invoke --name nonpd-aks-02 --resource-group 227925-dev-eus2-nonpd-rg --command "kubectl patch deployment resource-cache -n rtf --patch-file resource-cache-patch-file.yaml"
       
