name: Deploying Argocd

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

    #  - name: Build Docker image
    #    run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    #  - name: Push Docker image
    #    run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update guestbook-svc.yaml
        run: |
          cd argocd-files
          sed -i 's/guestbook-ui/guestbook-ui-svc-new/' guestbook-svc.yaml
          cat guestbook-svc.yaml
          git status
          git config --global user.name 'yumigm'
          git config --global user.email 'michael.yumiguani@us.nationalgrid.com'
          git add guestbook-svc.yaml
          git status
          git commit -m "Update guestbook.yaml"
          git push
