name: deployment file update

# Controls when the workflow will run

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 2

      - name: updating file
        run: |
          yes | sudo apt-get install xmlstarlet
          apiName="american-flights-api"
          cd additional-files
          
          echo "--------------------------------------"
          var=$(xmlstarlet select --omit-decl -t --copy-of '//plugin' rtf-dependencies.xml)
          echo $var
          xmlstarlet ed -s '//plugins' --type elem -n 'plugin' -v "$(xmlstarlet select --omit-decl -t --copy-of '//plugin' rtf-dependencies.xml)" testing.xml | xmlstarlet unescape> output.xml
          echo "printing output"
          cat output.xml
          xmlstarlet select -t --copy-of '//plugin' rtf-dependencies.xml > output2.xml
          cat output2.xml
